### ISSUE TITLE
Lua files in CraftOS-PC cause Lua Language Server to load infinitely

### ISSUE THREAD

**Issue by AngellusMortis** [MCJack123/vscode-craftos-pc#13]
No idea if there is anything you can do about this, but I figured since it is CraftOS PC specific it would be better to start here. The [Lua Language Server + extension](https://marketplace.visualstudio.com/items?itemName=sumneko.lua) has trouble handling files from CraftOS PC. 

It does not seem to matter if they are remote or local.

The only other notable thing is that I am using VS Code Remote with WSL (so VS Code is on the Windows host system, but it connects to the WSL Linux instance and CraftOS is also inside of WSL/running the Linux version). There are no other issues, the terminal and everything else still works. 

![image](https://user-images.githubusercontent.com/490848/166849668-e8ff8746-45bc-4c75-a1b8-1eded9300ed6.png)

The Loading workspace count and memory usage keeps climbing until VS Code slows down. I am guessing it is because the file CraftOS PC paths are not "real" (/ on the host system is a real Linux file system, so it is trying to index the whole file system).

**Comment by MCJack123** [comment]
This is an issue with the Lua extension not being able to handle virtual filesystems. I recommend you make an issue there if you want it to be fixed.

**Comment by AngellusMortis** [comment]
That is what I figured, but I do not know a lot about VS Code extensions so I figured I would start here since CC is kind of specialized.

**Comment by AngellusMortis** [comment]
Do you have any references in VS Code extension docs for how the virtual filesystem works?

**Comment by TimoXBeR** [comment]
hey, i might be too late, but i found solution. if you open remote files as a new workspace, the loading will only load files from your cc computer
