### ISSUE TITLE
Breakpoints not working in mounted files

### ISSUE THREAD

**Issue by DeVoidDev** [MCJack123/vscode-craftos-pc#19]
Hi, I just recently got started with using CraftOS-PC in combination with vscode.
I've wanted to try it for a while now, because it'd allow me to debug easier, and do it with a readonly mounted filesystem to avoid breaking project files.

Although, after trying it, it didn't seem to work with the builtin breakpoint functionality.

One possible solution would be to allow specifying a source:destination mapping in the workspace config for automounting.

Something like:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "craftos-pc",
            "request": "attach",
            "name": "Debug CraftOS-PC",
            "port": 0,
            "mount": {
                "src": "project"
            }
        }
    ]
}
```

Where `src` refers to the directory `${workspaceFolder}/src/`, and `project` refers to the mounted path `/project/` in the CraftOS-PC system.

I think adding this would allow much more flexibility with projects, and seperate design and runtime files without requiring a copy task (Which also allows semi-live reload).

**Comment by DeVoidDev** [comment]
After looking more into how the vscode debugger adapter works, it seems that this issue should be split in two, one in this repo for adding mount support to the launch config, and a second issue in [CraftOS-PC](https://github.com/MCJack123/craftos2) to resolve breakpoints to the original source path.

**Comment by MCJack123** [comment]
[I've created an issue on the main repo to track this.](https://github.com/MCJack123/craftos2/issues/327) The main concern is that mounts aren't being transferred over to the debugger host - once fixed, breakpoints should work fine in mounts,
