### ISSUE TITLE
`key_up` not being fired for certain keys

### ISSUE THREAD

**Issue by alexdevteam** [MCJack123/vscode-craftos-pc#2]
**Describe the bug**
The `key_up` is not sent for certain keys, such as Shift, the A, Q, W, E, R keys...

**To Reproduce**
1. Go into the lua interpreter
2. Type `while true do print(os.pullEvent("key_up")) end`
3. Watch how only certain keys trigger the `key_up` event, such as the D key.

**Expected behavior**
`key_up` should be triggered for each key of the keyboard (except escape).

**Screenshots**
Compares the extension with CraftOS-PC standalone. Notice how the `key_up` event isn't being triggered for keys 28, 30, 31, etc.
![image](https://user-images.githubusercontent.com/16354904/104810711-cbefe500-57f6-11eb-9ea2-9e49372708a5.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 1909
 - CraftOS-PC Version: v2.5.1.1
 - Compiled from source? No

**Additional context**
The same behaviour does not occur on the standalone version (Haven't tried on the web one because it freezes for me for some reason). This is an extension/binding issue and not a program core one, as far as I know.

**Comment by MCJack123** [comment]
Turns out the events were being misinterpreted when checking the keys on `key_up`, but not on `key`. This will be fixed in v2.5.2.
