### ISSUE TITLE
Virtual Workspace breaking extensions

### ISSUE THREAD

**Issue by Nogitsu** [MCJack123/vscode-craftos-pc#25]
Hey there,

I saw that the virtual workspace is breaking multiple extensions (like Lua server and your own CC autocompletion).

Would it be possible to add a setting permitting to take the virtual workspace to a local workspace ?
Maybe like storing it in a folder with an UUID and removing the folder on close.

**Comment by MCJack123** [comment]
That would require doing a bunch of network-intensive work that I frankly don't feel like doing. However, if you want to PR a solution, feel free to do so.
