### ISSUE TITLE
Crash when attaching peripheral

### ISSUE THREAD

**Issue by MrDj200** [MCJack123/vscode-craftos-pc#5]
Hey there, just wanted to attach a peripheral, but CraftOS-PC crashed when doing so.

When I try the same command in CraftOS-PC Standalone, it works though, that's why I'm posting here.

I tried: `attach top monitor` and `attach left debugger` 

I would attach the dump, but it's not being generated.

The only thing that might help with diagnosing is this:
![image](https://user-images.githubusercontent.com/5685500/119252112-b62a6c00-bbaa-11eb-8a35-9b4dfa2dfa3d.png)

This is a fresh installation of both the plugin and CraftOS-PC. Both with default settings.

**Comment by MCJack123** [comment]
This is a known issue, and was fixed in MCJack123/craftos2@a2f2663eb627002b9747a8c5a140be31140d5539. CraftOS-PC v2.5.6 will include this fix.
