### ISSUE TITLE
Error while trying to connect to remote instance

### ISSUE THREAD

**Issue by FancyBanana** [MCJack123/vscode-craftos-pc#7]
When I try to connect to a remote CraftOs (local sinngleplayer minecraft instance) I get `Could not connect to remote.craftos-pc.cc: certificate has expired` error.

![image](https://user-images.githubusercontent.com/7935263/141098587-0cfe402e-c437-4fe2-95a5-ec21d50cf079.png)

**Comment by FancyBanana** [comment]
After dong some code reading and some research I think this issue might be related: 
https://github.com/electron/electron/issues/31212

**Comment by FancyBanana** [comment]
I seem to have found a temporary solution: when setting this option is user settings in VSCode
```
"http.systemCertificates": false,
```
With this setting I successfully connected to a CraftOS computer inside my minecraft game.

**Comment by MCJack123** [comment]
It appears that this issue won't be fixed upstream for a little while, so the official solution will be to set `http.systemCertificates` in the config. I'll update the readme and documentation to notify about this.
